name: ludo_flutter
description: Ludo game with flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^2.3.2
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.3
  socket_io_client: ^3.1.2
  pusher_channels_flutter: ^2.4.0
  url_launcher: ^6.1.7
  flutter_stripe: ^10.0.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  cloud_firestore: ^5.6.6
  crypto: ^3.0.6
  audioplayers: ^6.4.0
  fluttertoast: ^8.2.12
  shared_preferences: ^2.2.2  # Update to the latest version if possible
  http: ^1.3.0
  font_awesome_flutter: ^10.8.0
  just_audio: ^0.10.0
  provider: ^6.1.4
  simple_ripple_animation: ^0.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  firebase_database: ^11.3.5

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/dice/
    - assets/images/crown/
    - assets/sounds/
    - assets/sounds/bg_music.mp3
    - assets/audio/bg_music.mp3
    - assets/sounds/match_found.mp3
    - assets/images/board.png

